### PR TITLE
Test more node versions in travis

### PR DESCRIPTION
**Pull request by Rayman**
I added some more node versions to test for and cleaned the travis script. The current version of node is v4.0.0 and roslib doesn't work on that due to an issue in Automattic/node-canvas#622. We could fix this with #194.

Version 1 and 2 are versions of io.js but apparently roslib works fine on there. Version 3 was the 'alpha' of node v4.

### CODE REVIEW

**Comment by rctoris** [comment]
Looks like the builds are failing

**Comment by Rayman** [comment]
I rebased and it looks like travis still fails but I'm unable to reproduce that issue on my machine. During an other build it looked like issue #114 occured again... https://travis-ci.org/Rayman/roslibjs/builds/80210067. I'll continue looking for a solution.

**Comment by Rayman** [comment]
I added the dependencies for chai and mocha and now everything works again.

**Comment by Rayman** [comment]
Rebase to fix a merge conflic in package.json

**Pull request merged**
