### PR TITLE
Upgraded EventEmitter2 and removed shim

### PR DESCRIPTION
**Pull request by eadlam**
I upgraded the EventEmitter2 version in package.json and removed the shim. This allows roslibjs to be used in webpack projects.

### CODE REVIEW

**Comment by rctoris** [comment]
Looks like no API changes which is awesome, have you run all of the examples?

**Comment by Rayman** [comment]
I think you forgot a couple of places:
- [ ] https://github.com/RobotWebTools/roslibjs/blob/develop/README.md#dependencies
- [ ] https://github.com/RobotWebTools/roslibjs/blob/develop/package.json#L10
- [ ] https://github.com/RobotWebTools/roslibjs/blob/develop/bower.json#L26
- [ ] examples/*.html hardcoded url
- [ ] https://github.com/RobotWebTools/roslibjs/blob/develop/test/require-shim.js#L3
- [ ] do the tests run? `npm test`
- [ ] do the examples run? `npm run test-examples`

**Comment by bduffany** [comment]
Status on this? I'm trying to use `roslibjs` with webpack as well and this PR solves my problems (I think).

**Comment by jihoonl** [comment]
Hi @eadlam, it looks like this PR was in conflict for a while. Could you rebase and apply @Rayman 's comments?

**Comment by subvertallchris** [comment]
Hey guys, would love to use this if anyone can finish it up.

**Comment by paulashbourne** [comment]
Any idea when this will be going into a new release?

**Pull request merged**
