### PR TITLE
Add deprecation warning in bower.json description

### PR DESCRIPTION
**Pull request by jihoonl**
As we discussed in #265, deprecation warning is added in bower module descrption.
@nuclearsandwich review and merge please.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I removed a word from the start of the description sentence that didn't fit with the rest of the sentence. With that change this looks good to me.

Good idea to remove the suggestion of using bower in the README as well 👍

**Comment by nuclearsandwich** [comment]
@jihoonl before I do something incorrect. You would like me to handle this merge correct?

**Comment by jihoonl** [comment]
Yes correct go ahead

**Comment by nuclearsandwich** [comment]
🎆

**Pull request merged**
