### PR TITLE
Add fail callback and missing docstrings to params

### PR DESCRIPTION
**Pull request by epaezrubio**

### CODE REVIEW

**Comment by epaezrubio** [comment]
I'm looking forward to some feedback about this PR 😃

**Comment by mvollrath** [comment]
Looks good, tests are unhappy though.

**Comment by epaezrubio** [comment]
I'm unsure how to run the tests. If I have done it correctly, the tests pass in my machine. Moreover, how are the failed fibonacci tests related to these changes?

**Comment by mvollrath** [comment]
This seems relevant: https://github.com/RobotWebTools/rosbridge_suite/issues/528

**Comment by MatthijsBurgh** [comment]
@EzraBrooks @sea-bass I think this PR is worth reviewing.

**Review by sea-bass — COMMENTED** [review]
I think this is a great addition.

Would you be able to modify the `simple.html` example to show this functionality?

**Review by EzraBrooks — APPROVED** [review]
This is a simple enough change, since it's just surfacing the underlying service callbacks, that I don't feel it needs additional testing or examples (given that the JSDoc comments indicate the usage). It's also an important addition - I myself have an application where I need to handle Param set failures in which I currently cannot without this change.

Thanks!

**Comment by MatthijsBurgh** [comment]
@EzraBrooks is this a breaking change? I need to know whether to include this change in the final v1 release.

**Comment by EzraBrooks** [comment]
This is non-breaking, it only added an optional argument.

**Pull request merged**
