### PR TITLE
Fix build attempt

### PR DESCRIPTION
**Pull request by viktorku**
The `develop` [build fails](https://travis-ci.org/RobotWebTools/roslibjs/builds/505181890), no idea why it wasn't picked up for the PR. This attempts to harmonize the mocha grunt config tasks.

### CODE REVIEW

**Comment by mvollrath** [comment]
The build works for me on develop, to get a clean build:

```
rm -rf node_modules
npm install
npm run publish
```

**Comment by mvollrath** [comment]
oic, a test may be legitimately failing now.

**Comment by mvollrath** [comment]
Mocha explodes when I `npm run test-workersocket` on this branch.

**Comment by viktorku** [comment]
@mvollrath does the `npm run test-workersocket` test pass on `develop` on your machine?

**Comment by mvollrath** [comment]
No, 3/4 fail:
```
Firefox 65.0.0 (Ubuntu 0.0.0) Topics Example Listening and publishing to a topic FAILED
	Error: Uncaught, unspecified 'error' event. (/home/matt/src/roslibjs/build/roslib.js:806)
Firefox 65.0.0 (Ubuntu 0.0.0) Topics Example unsubscribe doesn't affect other topics FAILED
	timeout of 1000ms exceeded. Ensure the done() callback is being called in this test.
Firefox 65.0.0 (Ubuntu 0.0.0) Topics Example unadvertise doesn't affect other topics FAILED
	timeout of 1000ms exceeded. Ensure the done() callback is being called in this test.
Firefox 65.0.0 (Ubuntu 0.0.0): Executed 4 of 4 (3 FAILED) (0 secs / NaN secs)
Firefox 65.0.0 (Ubuntu 0.0.0): Executed 4 of 4 (3 FAILED) (2.787 secs / NaN secs)
TOTAL: 3 FAILED, 1 SUCCESS
```

**Comment by mvollrath** [comment]
Same result on the worker_socket branch, I'll be fixing this.

**Comment by mvollrath** [comment]
The problem with local runs is the npm scripts only work in the context of the `test/build.bash` script, which calls another script to setup the backend.  These scripts don't clean up after themselves, I recommend running them in a container.

Scrolling back through the build history:

[This build](https://travis-ci.org/RobotWebTools/roslibjs/builds/505181890) appears to fail on something unrelated to workersocket.  Not sure why this would be, because it should rebuild just before running the test.

[This build](https://travis-ci.org/RobotWebTools/roslibjs/builds/505483584) has the same Mocha explosion I was experiencing.

**Comment by MatthijsBurgh** [comment]
This PR is stale and should be closed.

**Pull request closed without merging**
