### PR TITLE
Replace travis by GH actions

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Actions need to be enabled by maintainers

### CODE REVIEW

**Review by jihoonl — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
@jihoonl We need to change the branch protection rules to merge this. Could you do this or give me the rights to do this? (In case you update my rights, maybe best to keep this equal for roslibjs, ros2djs, and ros3djs.)

**Comment by jihoonl** [comment]
@MatthijsBurgh  I just disbled the travis ci from the branch protection rule. Would it be fine?

**Comment by MatthijsBurgh** [comment]
@jihoonl Yes we can merge this one. After the actions have completed, we should require GitHub actions to succeed in the branch protection.

**Comment by jihoonl** [comment]
You should be able to control all as of now. I reconfigure your rights to make it simple.

**Comment by jihoonl** [comment]
@MatthijsBurgh  what's your npm account?

**Comment by MatthijsBurgh** [comment]
@jihoonl I think it is the same as my GitHub username

**Comment by jihoonl** [comment]
@MatthijsBurgh  Ok thanks. you should have received the npm org invitation.

**Comment by MatthijsBurgh** [comment]
@jihoonl I haven't received the npm invite yet. I am not sure npm is case sensitive. My npm account is 'matthijsburgh'

**Comment by MatthijsBurgh** [comment]
@jihoonl I got 9 invites 😄, Invite accepted

**Comment by jihoonl** [comment]
@MatthijsBurgh Ooops. 😅 

You should have access to the npm modules as of now too. 😉

**Pull request merged**
