### PR TITLE
1.0.0

### LINKED ISSUE #311: Release major version (1.0)
Dependent projects interested in keeping up with fixes and optimizations to roslibjs have to specify exact versions and re-release for every roslibjs release to stay up to date.  If roslibjs were given a major version, dependent packages could use looser version requirements without risk of breaking interface changes.  This is extremely valuable to projects which use or wrap roslibjs such as [ros-websocket](https://github.com/EndPointCorp/ros-websocket) and [ros3djs](https://github.com/RobotWebTools/ros3djs).

### PR DESCRIPTION
**Pull request by mvollrath**
Fixes #311

### CODE REVIEW

**Comment by jihoonl** [comment]
@mvollrath what's your npm id? I will add you to npm org so can release the library in npm

**Comment by jihoonl** [comment]
@viktorku Would you take a look? and what's your npm id as well?

**Comment by mvollrath** [comment]
https://www.npmjs.com/~mdevolving

**Comment by mvollrath** [comment]
I should now update the builds and push a tag?

**Comment by jihoonl** [comment]
yup. That would be great.

**Pull request merged**
