### PR TITLE
Use webworkify-webpack with webpack

### LINKED ISSUE #382: Issue with roslibjs and Webpack 5
I am using roslibjs for one of my projects that is currently trying to upgrade to Webpack 5 and I am running into some issues.

I've created a minimum reproducible project here:
https://github.com/amosbyon1224/roslib-webpack5

but the main issue seems to be with `webworkify` complaining about `arguments` being undefined.

roslibjs was working fine using webpack 4.27.1  but is now broken using webpack 5.6.0

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Fixes #382

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@jihoonl @mvollrath @J-Rojas any comments?

**Comment by HiggsWRX** [comment]
I absolutely love this PR. You saved my bacon with this PR. Bless you

**Comment by PhilippeMorier** [comment]
Hi @MatthijsBurgh :wave:!

* Do you already know when this fix will be released?
* What can I do in the meanwhile?

Thanks a lot!

**Comment by MatthijsBurgh** [comment]
It has been released.

**Comment by PhilippeMorier** [comment]
Amazing :tada:!

Thanks a lot :pray:!

**Pull request merged**
