### PR TITLE
Split `publish` NPM hook into `prepublishOnly` and `prepare`

### LINKED ISSUE #714: Develop branch doesn't work with npm - React
**Description**
React: NPM doesn't package roslib properly when using "npm install" after specifying latest 'develop' commit in package.json

- Library Version: develop branch - latest commit
- ROS Version: Iron
- Platform / OS: Ubuntu 22.04 LTS

**Steps To Reproduce**

I'm developing a web interface using roslibjs within React. I decided to use the "develop" branch for ROS2 support, as the "ros2" branch hasn't been updated in years. To do this, I specified the commit SHA in the package.json file, using the following syntax and command:

"roslib": "github:RobotWebTools/roslibjs#253ae642782bddb3f942b19dc6462007d9f249c7",
$ npm install

I had been using an older commit (the one shown above) as **the most recent "develop" commit doesn't seem to package roslib properly with NPM;** the pictures below of the VS Code file explorer should highlight the issue. Due to this issue, I was unable to import roslib functionality and had to revert to the older commit.

That older commit had been working fine, but there was an issue with how the lib was using "Websocket" in the node_modules/roslib/src/core/Ros.js file. If I attempted to reconnect to the rosbridge using the same "Ros" object, the "WebSocket.CLOSED" used in the comparison on line 76 causes the following issue:
file:///home/ramiqamhieh/Pictures/Screenshots/Screenshot%20from%202024-04-16%2015-25-27.png
**This WebSocket issue is irrelevant; this is simply the reason I decided to try to switch to the most recent commit.**

**Expected Behavior**
From 'develop' commit I had been using (253ae642782bddb3f942b19dc6462007d9f249c7)
/node_modules/roslib
image

**Actual Behavior**
**The /src directory is missing**
From latest 'develop' commit (cf1f5ada69e9f3f8e22887ffb000b0ca2dfc2277)
/node_modules/roslib
image

Full package.json file:
```json
{
  "name": "ros2bridge",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "ol": "^8.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.3",
    "react-scripts": "^5.0.1",
    "roslib": "github:RobotWebTools/roslibjs#cf1f5ada69e9f3f8e22887ffb000b0ca2dfc2277",
    "styled-components": "^6.1.8",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by EzraBrooks**
**Public API Changes**

None.

**Description**

Closes #714. Currently, installing this package via Git triggers some unwanted lifecycle hooks. This makes `npm` or `pnpm` `install roslib@github:RobotWebTools/roslibjs#develop` work.

### CODE REVIEW

**Comment by EzraBrooks** [comment]
@ramiCMT does installing this branch via NPM work for you? it seems to work for me via PNPM.

**Comment by RamiCMT** [comment]
> @RamiCMT does installing this branch via NPM work for you? it seems to work for me via PNPM.

Following the steps outlined in issue #714, it doesn't seem to work --> still missing the /src directory

**Comment by RamiCMT** [comment]
> @RamiCMT does installing this branch via NPM work for you? it seems to work for me via PNPM.

This is what I'm seeing:
image

I may need to update my import syntax, I will circle back if I can get that working...

**Comment by EzraBrooks** [comment]
That output _should_ work without the `src` directory; There's no reference to `src` in the `package.json`'s entrypoints. Are you not able to require/import this into your application for some reason?

**Comment by RamiCMT** [comment]
> That output _should_ work without the `src` directory; There's no reference to `src` in the `package.json`'s entrypoints. Are you not able to require/import this into your application for some reason?

The proposed changes work! :)

I had to update some of my imports - seems like 'ServiceRequest' and 'Message' objects are no longer required

Thanks for the help!!

**Comment by EzraBrooks** [comment]
Correct, we removed those interstitial types since they were just syntactic sugar around user-provided types and made it hard to implement TypeScript generics for the services, topics, etc.

Glad I could help!

**Comment by MatthijsBurgh** [comment]
@EzraBrooks what is the new release procedure?

_update_: The npm docs from #714 explained these changes.

**Review by MatthijsBurgh — APPROVED** [review]

**Pull request merged**
